#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 

bspc config border_width         2
bspc config focused_border_color "#98971a"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart applications

#picom --config $HOME/.config/picom/picom.conf & 
#nitrogen --restore & 
#Hotkey
sxhkd & 
#compfy & 


feh --bg-fill --randomize ~/Pictures/Wallpapers/ & 

dunst & 
polybar topbar &
picom & 
ibus-setup
